// flow-typed signature: 53b386613f6dc04e23c4ecd7022687ba
// flow-typed version: <<STUB>>/normalize.css_v^8.0.1/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'normalize.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'normalize.css' {
  declare module.exports: any;
}
